#!/usr/bin/env python3
import os
import re

def normalize_html(html_str):
    # Strip autogenerated generator meta tags or id attributes if auto-generated
    html_str = re.sub(r'<meta name="generator"[^>]+>', '', html_str)
    # Strip trailing whitespace and blank lines
    lines = [line.strip() for line in html_str.splitlines() if line.strip()]
    return '\n'.join(lines)

files = [
    'golden-spooky-dark.html',
    'golden-spooky-light.html',
    'golden-blog.html',
    'golden-doc.html',
    'coastal-radio/golden-nested.html'
]

print("=== Normalized HTML Structural Comparison ===")
for f in files:
    p_path = os.path.join('apex-spike/clean-run/pandoc_baseline_output', f)
    a_path = os.path.join('apex-spike/clean-run/apex_output', f)

    with open(p_path, 'r', encoding='utf-8') as pf:
        p_html = normalize_html(pf.read())
    with open(a_path, 'r', encoding='utf-8') as af:
        a_html = normalize_html(af.read())

    print(f"\n--- File: {f} ---")
    if p_html == a_html:
        print("✓ PASS: Identical normalized HTML output.")
    else:
        print("~ STRUCTURAL DIFFERENCE DETECTED:")
        p_lines = p_html.splitlines()
        a_lines = a_html.splitlines()
        print(f"  Pandoc line count: {len(p_lines)} | Apex adapter line count: {len(a_lines)}")
