/**
 * ast_json.h - Conversion helpers between cmark-gfm AST and
 *              a Pandoc-compatible JSON AST.
 *
 * The JSON format follows Pandoc's JSON representation as documented at:
 *   https://pandoc.org/filters.html#summary
 *
 * We currently support a practical subset of Block/Inline constructors
 * (Paragraphs, Headers, Lists, Code blocks, Raw HTML, Emphasis, Links, etc.).
 * Unsupported nodes are conservatively rendered as plain text.
 */

#ifndef APEX_AST_JSON_H
#define APEX_AST_JSON_H

#include "cmark-gfm.h"
#include "apex/apex.h"

/**
 * Serialize a cmark-gfm document node into a Pandoc-compatible JSON AST.
 *
 * @param document  Root cmark document node (CMARK_NODE_DOCUMENT).
 * @param options   Apex options used for this render (may be NULL).
 * @return Newly allocated JSON string or NULL on error.
 *         Caller must free with free().
 */
char *apex_cmark_to_pandoc_json(cmark_node *document,
                                const apex_options *options);

/**
 * Parse a Pandoc-compatible JSON AST into a new cmark-gfm document node.
 *
 * The parser expects the same structural subset that is generated by
 * apex_cmark_to_pandoc_json. JSON produced by well-behaved Pandoc-style
 * filters that preserve this structure will round-trip correctly.
 *
 * @param json      UTF-8 JSON string.
 * @param options   Apex options used for this render (may be NULL).
 * @return New CMARK_NODE_DOCUMENT tree on success, or NULL on error.
 *         Caller must free with cmark_node_free().
 */
cmark_node *apex_pandoc_json_to_cmark(const char *json,
                                      const apex_options *options);

#endif /* APEX_AST_JSON_H */

