#!/usr/bin/env python3
# ==============================================================================
#  COMPARISON SCRIPT: compare_output.py
#  Purpose: Compares normalized HTML output between Pandoc and Apex adapter.
# ==============================================================================

import os
import sys
import re
from pathlib import Path

ADAPTER_DIR = Path(__file__).resolve().parent
SPIKE_DIR = ADAPTER_DIR.parent
DEFAULT_PANDOC_DIR = SPIKE_DIR / "outputs" / "pandoc_baseline"
DEFAULT_APEX_DIR = SPIKE_DIR / "outputs" / "apex"

def normalize_html(html_str):
    """Strip autogenerated metadata tags and normalize whitespace."""
    html_str = re.sub(r'<meta name="generator"[^>]+>', '', html_str)
    lines = [line.strip() for line in html_str.splitlines() if line.strip()]
    return '\n'.join(lines)

def compare_directories(pandoc_dir, apex_dir):
    pandoc_dir = Path(pandoc_dir)
    apex_dir = Path(apex_dir)

    if not pandoc_dir.exists() or not apex_dir.exists():
        print(f"Directory missing: Pandoc dir exists={pandoc_dir.exists()}, Apex dir exists={apex_dir.exists()}")
        return False

    files = [
        'golden-spooky-dark.html',
        'golden-spooky-light.html',
        'golden-blog.html',
        'golden-doc.html',
        'coastal-radio/golden-nested.html'
    ]

    print("=== Normalized HTML Structural Comparison ===")
    all_identical = True

    for rel_path in files:
        p_path = pandoc_dir / rel_path
        a_path = apex_dir / rel_path

        if not p_path.is_file() or not a_path.is_file():
            print(f"Skipping {rel_path} (file not generated yet)")
            continue

        with open(p_path, 'r', encoding='utf-8') as pf:
            p_html = normalize_html(pf.read())
        with open(a_path, 'r', encoding='utf-8') as af:
            a_html = normalize_html(af.read())

        print(f"\n--- File: {rel_path} ---")
        if p_html == a_html:
            print("✓ PASS: Identical normalized HTML output.")
        else:
            all_identical = False
            p_lines = p_html.splitlines()
            a_lines = a_html.splitlines()
            print(f"~ STRUCTURAL DIFFERENCE DETECTED:")
            print(f"  Pandoc line count: {len(p_lines)} | Apex adapter line count: {len(a_lines)}")

    return all_identical

if __name__ == '__main__':
    p_dir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PANDOC_DIR
    a_dir = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_APEX_DIR
    compare_directories(p_dir, a_dir)
