#!/usr/bin/env bash
# rc-dip.sh: Document Improvement Project
# Discovers core files, stubs missing docs, and whisks obsolete docs to safety.

set -euo pipefail

# Source utilities if available
[ -f "bones/scripts/rc-utils.sh" ] && source "bones/scripts/rc-utils.sh"

if [[ "${1:-}" == "--dry-run" ]]; then
  exit 0
fi

DOCS_DIR="home/content/docs"
OBSOLETE_DIR="home/content/obsolete/docs"
WHITELIST_FILE="bones/config/dip-whitelist.txt"
MATRIX_FILE="${DOCS_DIR}/dip-matrix.md"
DATE_STR=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

log_msg() {
    echo "[DIP] $1"
}

log_msg "Starting Document Improvement Project audit..."

# 1. Discover Core Files (ignoring home/content, output, bones/reports, etc)
mapfile -t FOUND_FILES < <(
  find . \
    \( -type d \( \
      -name '.git' -o \
      -name '.github' -o \
      -name '.vscode' -o \
      -name '.idea' -o \
      -path './home/content' -o \
      -path './home/assets' -o \
      -path './output' -o \
      -path './bones/reports' -o \
      -path './bones/logs' -o \
      -path './bones/archive' -o \
      -path './bones/releases' -o \
      -path './bones/ingested' -o \
      -path './bones/tmp' -o \
      -path './messages-from-my-friends' -o \
      -path './tmp' \
    \) -prune \) -o \
    \( -type f ! -name '.*' -print \) | sed 's|^\./||'
)

# Extract core files and core md files
CORE_FILES=()
CORE_MD_FILES=()
for file in "${FOUND_FILES[@]}"; do
  # Filter out specific file types
  if [[ "$file" =~ \.(png|css|md|DS_Store|db)$ ]]; then
    # If it's a top-level uppercase markdown file, add it to CORE_MD_FILES
    if [[ "$file" =~ ^[A-Z]+\.md$ ]]; then
      CORE_MD_FILES+=("$file")
    fi
    continue
  fi
  CORE_FILES+=("$file")
done

ALL_CORE_FILES=$(printf '%s
' "${CORE_FILES[@]}" "${CORE_MD_FILES[@]}" | sort | uniq | grep -v '^$')

# Create a map of expected doc files
declare -A EXPECTED_DOCS

for file in $ALL_CORE_FILES; do
    # Map file path to expected doc path:
    # rotkeeper.sh -> home/content/docs/rotkeeper.md
    # bones/scripts/rc-render.sh -> home/content/docs/bones/scripts/rc-render.md

    # Remove file extension and replace with .md
    BASE_NO_EXT="${file%.*}"
    # If the file has no extension (like some python scripts or just a file), handle it
    if [ "$BASE_NO_EXT" == "$file" ]; then
        DOC_PATH="${DOCS_DIR}/${file}.md"
    else
        DOC_PATH="${DOCS_DIR}/${BASE_NO_EXT}.md"
    fi

    EXPECTED_DOCS["$DOC_PATH"]="$file"
done

# Read whitelist
declare -A WHITELISTED_DOCS
if [ -f "$WHITELIST_FILE" ]; then
    while IFS= read -r line; do
        # Ignore empty lines and comments
        [[ -z "$line" || "$line" == \#* ]] && continue
        WHITELISTED_DOCS["$line"]=1
    done < "$WHITELIST_FILE"
fi

# 2. Whisk Obsolete Docs
log_msg "Checking for obsolete docs..."
EXISTING_DOCS=$(find "$DOCS_DIR" -type f -name "*.md" | grep -v "$MATRIX_FILE" || true)

for doc in $EXISTING_DOCS; do
    # Is it in expected docs?
    if [ -z "${EXPECTED_DOCS["$doc"]:-}" ]; then
        # Not expected. Is it whitelisted?
        if [ -z "${WHITELISTED_DOCS["$doc"]:-}" ]; then
            # Not whitelisted. Whisk it away!
            # Calculate path relative to DOCS_DIR
            REL_PATH="${doc#"$DOCS_DIR"/}"
            DEST_PATH="${OBSOLETE_DIR}/${REL_PATH}"
            DEST_DIR=$(dirname "$DEST_PATH")

            mkdir -p "$DEST_DIR"
            mv "$doc" "$DEST_PATH"
            log_msg "Whisked obsolete doc: $doc -> $DEST_PATH"
        fi
    fi
done

# 3. Stub Missing Docs
log_msg "Stubbing missing docs..."
for doc_path in "${!EXPECTED_DOCS[@]}"; do
    target_file="${EXPECTED_DOCS[$doc_path]}"

    if [ ! -f "$doc_path" ]; then
        DOC_DIR=$(dirname "$doc_path")
        mkdir -p "$DOC_DIR"

        # Determine title
        TITLE=$(basename "$target_file")

        cat << STUB > "$doc_path"
---
title: "$TITLE Documentation"
target_file: "$target_file"
date: "$DATE_STR"
template: "rotkeeper-doc.html"
status: "stub"
---

# $TITLE

Documentation for \`$target_file\`. This file was auto-generated by the Document Improvement Project (DIP).

## Overview
TODO: Provide a brief overview of what this file does.

## Details
TODO: Provide technical details, usage instructions, or context.
STUB
        log_msg "Stubbed missing doc: $doc_path"
    fi
done

# 4. Check Formatting & Generate Matrix
log_msg "Generating DIP Matrix at $MATRIX_FILE..."

cat << 'MATRIX' > "$MATRIX_FILE"
---
title: "Document Improvement Project (DIP) Matrix"
date: "GENERATED_DATE"
template: "rotkeeper-doc.html"
---

# Document Improvement Project Matrix

This page tracks the documentation status of core project files.

| Target File | Doc Page | Last Code Edit | Last Doc Edit | Status |
|-------------|----------|----------------|---------------|--------|
MATRIX

sed -i "s/GENERATED_DATE/$DATE_STR/" "$MATRIX_FILE"

# Helper to get filesystem modified date
get_fs_date() {
    local file=$1
    if [ -f "$file" ]; then
        date -r "$file" "+%Y-%m-%d"
    else
        echo "Missing"
    fi
}

for doc_path in $(find "$DOCS_DIR" -type f -name "*.md" | grep -v "$MATRIX_FILE" | sort); do
    target_file=""
    status="OK"

    # Try to extract target_file from frontmatter
    if grep -q "^target_file:" "$doc_path"; then
        target_file=$(grep "^target_file:" "$doc_path" | awk -F'"' '{print $2}' || grep "^target_file:" "$doc_path" | awk '{print $2}')
    else
        # Reverse lookup from EXPECTED_DOCS
        target_file="${EXPECTED_DOCS[$doc_path]:-}"
    fi

    # Check if whitelisted
    if [ -n "${WHITELISTED_DOCS[$doc_path]:-}" ]; then
        target_file="(Whitelisted)"
    fi

    # Determine dates
    doc_date=$(get_fs_date "$doc_path")
    code_date="N/A"
    if [ -n "$target_file" ] && [ "$target_file" != "(Whitelisted)" ] && [ -f "$target_file" ]; then
        code_date=$(get_fs_date "$target_file")
    fi

    # Very basic format check (has frontmatter?)
    if ! grep -q "^---" "$doc_path"; then
        status="Missing Frontmatter"
    elif grep -q 'status: "stub"' "$doc_path"; then
        status="Stub"
    fi

    # Print row
    rel_doc=${doc_path#"$DOCS_DIR"/}
    echo "| \`$target_file\` | [$rel_doc]($rel_doc) | $code_date | $doc_date | $status |" >> "$MATRIX_FILE"
done

log_msg "DIP audit complete. See $MATRIX_FILE for details."
