#!/usr/bin/env bash
# ============================================================
#  ██████╗ ██╗██████╗
#  ██╔══██╗██║██╔══██╗
#  ██║  ██║██║██████╔╝
#  ██║  ██║██║██╔═══╝
#  ██████╔╝██║██║
#  ╚═════╝ ╚═╝╚═╝
# ============================================================
#  Project : Rotkeeper
#  Repo    : https://github.com/drawmeanelephant/rotkeeper
#  Script  : rc-dip.sh
#  Purpose : Document Improvement Project - audits and fixes docs
#  Version : 0.3.1.4
#  Updated : 2026-03-23
# ------------------------------------------------------------
#  Part of the Rotkeeper ritual system — bones, scripts, tombs.
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source utilities and env if available
if [[ -f "$SCRIPT_DIR/rc-utils.sh" ]]; then
    source "$SCRIPT_DIR/rc-utils.sh"
else
    echo "FATAL: cannot source rc-utils.sh" >&2
    exit 1
fi

if [[ -f "$SCRIPT_DIR/rc-env.sh" ]]; then
    source "$SCRIPT_DIR/rc-env.sh"
else
    echo "FATAL: cannot source rc-env.sh" >&2
    exit 1
fi

rk_init_script rc-dip "$@"

OBSOLETE_DIR="${CONTENT_DIR}/obsolete/docs"
WHITELIST_FILE="${CONFIG_DIR}/dip-whitelist.txt"
# shellcheck disable=SC2153
MATRIX_FILE="${DOCS_DIR}/dip-matrix.md"
DATE_STR=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

log "INFO" "Starting Document Improvement Project audit..."

# 1. Discover Core Files
mapfile -d '' FOUND_FILES < <(
  find "$ROOT_DIR" \
    \( -type d \( \
      -name '.git' -o \
      -name '.github' -o \
      -name '.vscode' -o \
      -name '.idea' -o \
      -path "$CONTENT_DIR" -o \
      -path "$ASSETS_DIR" -o \
      -path "$OUTPUT_DIR" -o \
      -path "$REPORT_DIR" -o \
      -path "$LOG_DIR" -o \
      -path "$ARCHIVE_DIR" -o \
      -path "${BONES_DIR}/releases" -o \
      -path "${BONES_DIR}/ingested" -o \
      -path "${BONES_DIR}/tmp" -o \
      -path "$ROOT_DIR/messages-from-my-friends" -o \
      -path "$ROOT_DIR/tmp" \
    \) -prune \) -o \
    \( -type f ! -name '.*' -print0 \)
)

CORE_FILES=()
for file in "${FOUND_FILES[@]}"; do
  rel_file="${file#"$ROOT_DIR/"}"
  if [[ "$rel_file" =~ \.(png|css|md|DS_Store|db)$ ]]; then
    if [[ "$rel_file" =~ ^[A-Z]+\.md$ ]]; then
      CORE_FILES+=("$rel_file")
    fi
    continue
  fi
  CORE_FILES+=("$rel_file")
done

declare -A EXPECTED_DOCS
for file in "${CORE_FILES[@]}"; do
    BASE_NO_EXT="${file%.*}"
    if [ "$BASE_NO_EXT" == "$file" ]; then
        DOC_PATH="${DOCS_DIR}/${file}.md"
    else
        DOC_PATH="${DOCS_DIR}/${BASE_NO_EXT}.md"
    fi
    EXPECTED_DOCS["$DOC_PATH"]="$file"
done

declare -A WHITELISTED_DOCS
if [ -f "$WHITELIST_FILE" ]; then
    while IFS= read -r line; do
        [[ -z "$line" || "$line" == \#* ]] && continue
        WHITELISTED_DOCS["$ROOT_DIR/$line"]=1
    done < "$WHITELIST_FILE"
fi

# 2. Whisk Obsolete Docs
log "INFO" "Checking for obsolete docs..."
mapfile -d '' EXISTING_DOCS < <(find "$DOCS_DIR" -type f -name "*.md" -print0)

for doc in "${EXISTING_DOCS[@]}"; do
    [[ "$doc" == "$MATRIX_FILE" ]] && continue

    if [[ -z "${EXPECTED_DOCS["$doc"]:-}" ]]; then
        if [[ -z "${WHITELISTED_DOCS["$doc"]:-}" ]]; then
            REL_PATH="${doc#"$DOCS_DIR"/}"
            DEST_PATH="${OBSOLETE_DIR}/${REL_PATH}"
            DEST_DIR=$(dirname "$DEST_PATH")

            if [[ "${DRY_RUN:-false}" == true ]]; then
                log "DRY-RUN" "Would whisk obsolete doc: $doc -> $DEST_PATH"
            else
                mkdir -p "$DEST_DIR"
                mv "$doc" "$DEST_PATH"
                log "INFO" "Whisked obsolete doc: $doc -> $DEST_PATH"
            fi
        fi
    fi
done

# 3. Stub Missing Docs
log "INFO" "Stubbing missing docs..."
for doc_path in "${!EXPECTED_DOCS[@]}"; do
    target_file="${EXPECTED_DOCS[$doc_path]}"

    if [ ! -f "$doc_path" ]; then
        if [[ "${DRY_RUN:-false}" == true ]]; then
            log "DRY-RUN" "Would stub missing doc: $doc_path"
        else
            DOC_DIR=$(dirname "$doc_path")
            mkdir -p "$DOC_DIR"

            TITLE=$(basename "$target_file")

            cat << STUB > "$doc_path"
---
title: "$TITLE Documentation"
target_file: "$target_file"
date: "$DATE_STR"
template: "rotkeeper-doc.html"
status: "stub"
version: "0.1.0"
author: "Rotkeeper DIP"
project: "Rotkeeper"
---

# $TITLE

Documentation for \`$target_file\`. This file was auto-generated by the Document Improvement Project (DIP).

## Overview
<!-- DIP-GENERATED-MARKER: Overview -->
TODO: Provide a brief overview of what this file does.

## Details
<!-- DIP-GENERATED-MARKER: Details -->
TODO: Provide technical details, usage instructions, or context.
STUB
            log "INFO" "Stubbed missing doc: $doc_path"
        fi
    fi
done

# 4. Check Formatting & Generate Matrix
log "INFO" "Generating DIP Matrix at $MATRIX_FILE..."

if [[ "${DRY_RUN:-false}" == true ]]; then
    log "DRY-RUN" "Would generate DIP matrix at $MATRIX_FILE"
else
    cat << 'MATRIX' > "$MATRIX_FILE"
---
title: "Document Improvement Project (DIP) Matrix"
date: "GENERATED_DATE"
template: "rotkeeper-doc.html"
---

# Document Improvement Project Matrix

This page tracks the documentation status of core project files.

| Target File | Doc Page | Last Code Edit | Last Doc Edit | Status |
|-------------|----------|----------------|---------------|--------|
MATRIX

    sed -i "s/GENERATED_DATE/$DATE_STR/" "$MATRIX_FILE"
fi

get_fs_date() {
    local file=$1
    if [ -f "$file" ]; then
        date -r "$file" "+%Y-%m-%d"
    else
        echo "MISSING"
    fi
}

mapfile -d '' MATRIX_DOCS < <(find "$DOCS_DIR" -type f -name "*.md" -print0)
mapfile -t sorted_docs < <(printf '%s
' "${MATRIX_DOCS[@]}" | sort)

for doc_path in "${sorted_docs[@]}"; do
    [[ -z "$doc_path" ]] && continue
    [[ "$doc_path" == "$MATRIX_FILE" ]] && continue

    target_file=""
    status="OK"

    if grep -q "^target_file:" "$doc_path"; then
        target_file=$(grep "^target_file:" "$doc_path" | awk -F'"' '{print $2}' || grep "^target_file:" "$doc_path" | awk '{print $2}')
    else
        target_file="${EXPECTED_DOCS[$doc_path]:-}"
    fi

    is_expected=0
    if [[ -n "${EXPECTED_DOCS[$doc_path]:-}" ]]; then
        is_expected=1
    fi

    is_whitelisted=0
    if [[ -n "${WHITELISTED_DOCS[$doc_path]:-}" ]]; then
        is_whitelisted=1
    fi

    doc_date=$(get_fs_date "$doc_path")
    code_date="N/A"

    if [[ "$is_whitelisted" -eq 1 ]]; then
        status="Whitelisted"
        if [[ -z "$target_file" ]]; then
            target_file="(Whitelisted)"
        elif [[ "$target_file" != "(Whitelisted)" ]]; then
            if [[ ! -f "$ROOT_DIR/$target_file" ]]; then
                status="Missing Target"
                code_date="MISSING"
            else
                code_date=$(get_fs_date "$ROOT_DIR/$target_file")
            fi
        fi
    elif [[ "$is_expected" -eq 0 ]]; then
        status="Orphaned"
    elif [[ -n "$target_file" && ! -f "$ROOT_DIR/$target_file" ]]; then
        status="Missing Target"
        code_date="MISSING"
    else
        if [[ -n "$target_file" && -f "$ROOT_DIR/$target_file" ]]; then
            code_date=$(get_fs_date "$ROOT_DIR/$target_file")
        fi
        if ! grep -q "^---" "$doc_path"; then
            status="Missing Frontmatter"
        elif grep -q '^status:[[:space:]]*"stub"' "$doc_path" || grep -q "^status:[[:space:]]*stub" "$doc_path"; then
            if grep -q "TODO:" "$doc_path"; then
                status="Stub"
            else
                status="Stub+Content"
            fi
        fi
    fi

    rel_doc="${doc_path#"$DOCS_DIR"/}"

    if [[ "${DRY_RUN:-false}" == true ]]; then
        log "DRY-RUN" "Would matrix row: | \`$target_file\` | [$rel_doc]($rel_doc) | $code_date | $doc_date | $status |"
    else
        echo "| \`$target_file\` | [$rel_doc]($rel_doc) | $code_date | $doc_date | $status |" >> "$MATRIX_FILE"
    fi
done

if [[ "${DRY_RUN:-false}" == false ]]; then
    log "INFO" "DIP audit complete. See $MATRIX_FILE for details."
fi
