#!/usr/bin/env bash
# ============================================================
#  ██████╗  ██████╗ ████████╗██╗  ██╗███████╗███████╗██████╗
#  ██╔══██╗██╔═══██╗╚══██╔══╝██║ ██╔╝██╔════╝██╔════╝██╔══██╗
#  ██████╔╝██║   ██║   ██║   █████╔╝ █████╗  █████╗  ██████╔╝
#  ██╔══██╗██║   ██║   ██║   ██╔═██╗ ██╔══╝  ██╔══╝  ██╔═══╝
#  ██║  ██║╚██████╔╝   ██║   ██║  ██╗███████╗███████╗██║
#  ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝
# ============================================================
#  Project : Rotkeeper
#  Repo    : https://github.com/drawmeanelephant/rotkeeper
#  Script  : rc-index.sh
#  Purpose : Index all HTML output docs, binder ritual style
#  Version : 0.3.0.13
#  Updated : 2026-03-23
# ------------------------------------------------------------
#  Part of the Rotkeeper ritual system — bones, scripts, tombs.
# ============================================================

# set -euo pipefail
# trap 'echo "Error on line $LINENO"; exit 1' ERR

# Load environment (update path as needed)
source "$(dirname "${BASH_SOURCE[0]}")/rc-utils.sh"
require_gawk_version

DRY_RUN=false

show_help() {
  cat <<EOF
Usage: rc-index.sh [--dry-run] [--help]

  --dry-run    Just show what would be indexed, don’t write files
  --help       Show this help message
EOF
}

parse_flags() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) DRY_RUN=true; shift ;;
      --help) show_help; exit 0 ;;
      *) echo "Unknown option: $1"; show_help; exit 1 ;;
    esac
  done
}

parse_flags "$@"

# Output locations
BINDER_MD="$REPORT_DIR/output-html-binder.md"
INDEX_HTML="$REPORT_DIR/output-html-index.html"

echo "[INFO] Scanning for HTML files in $OUTPUT_DIR..."
mapfile -d '' -t html_files < <(find "$OUTPUT_DIR" -type f -name '*.html' -print0 | sort -z)

# --- DEBUG OUTPUT ---
echo "[DEBUG] OUTPUT_DIR is: $OUTPUT_DIR"
echo "[DEBUG] REPORT_DIR is: $REPORT_DIR"
echo "[DEBUG] Files found: ${#html_files[@]}"
for x in "${html_files[@]}"; do
  echo "[DEBUG] -> $x"
done

# If no files found, log warning and exit early after writing headers/footers
if [[ "${#html_files[@]}" -eq 0 ]]; then
  # Write binder header
  {
    echo "# Output HTML Binder"
    echo "_Generated by rc-index.sh on $(date)_"
    echo ""
    echo "_No HTML files found in output/._"
  } > "$BINDER_MD"
  # Write HTML index header/footer
  {
    echo "<!DOCTYPE html>"
    echo "<html><head><meta charset=\"UTF-8\"><title>Output Index</title></head><body>"
    echo "<h1>Site Output Index</h1>"
    echo "<p><em>No HTML pages found in the output directory.</em></p>"
    echo "</body></html>"
  } > "$INDEX_HTML"
  echo "[WARN] No HTML files found. Exiting early."
  exit 0
fi

if [[ "$DRY_RUN" == true ]]; then
  echo "[DRY-RUN] Would index the following files:"
  for file in "${html_files[@]}"; do
    echo "  $file"
  done
  exit 0
fi

echo "[INFO] Building index and binder from discovered HTML files..."
echo "[INFO] Creating Markdown binder at: $BINDER_MD"
echo "[INFO] Creating HTML index at: $INDEX_HTML"

# Write binder header
{
  echo "# Output HTML Binder"
  echo "_Generated by rc-index.sh on $(date)_"
  echo ""
} > "$BINDER_MD"

# Write HTML index header
{
  echo "<!DOCTYPE html>"
  echo "<html><head><meta charset=\"UTF-8\"><title>Output Index</title></head><body>"
  echo "<h1>Site Output Index</h1>"
} > "$INDEX_HTML"

total_pages=0

for file in "${html_files[@]}"; do
  total_pages=$((total_pages + 1))
  rel_path="${file#$OUTPUT_DIR/}"
  echo "[INFO] Processing: $rel_path"

  # Extract title from <title> tag
  page_title="$(sed -n '/<title>/,/<\/title>/p' "$file" | sed -e 's/<[\/]*title>//g' | tr -d '\n' | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  [[ -z "$page_title" ]] && page_title="(untitled page)"

  # Add to HTML index
  echo "<li><a href=\"../../output/$rel_path\">$rel_path</a> — $page_title</li>" >> "$INDEX_HTML"

  # Add to Markdown binder
  {
    echo "## $rel_path"
    echo ""
    echo '```text'
    if ! pandoc "$file" -f html -t plain 2>/dev/null; then
      echo "[WARN] Could not convert: $rel_path"
    fi
    echo '```'
    echo ""
  } >> "$BINDER_MD"
  echo "[DEBUG] Finished: $rel_path"
done

if [[ "$total_pages" -eq 0 ]]; then
  echo "<p><em>No HTML pages found in the output directory.</em></p>" >> "$INDEX_HTML"
  echo "_No HTML files found in output/._" >> "$BINDER_MD"
fi

# Footer
echo "</body></html>" >> "$INDEX_HTML"
echo "_End of binder — generated by rc-index.sh at $(date)_" >> "$BINDER_MD"

echo "[INFO] Indexed $total_pages pages."

